### ISSUE TITLE
problem importing yeast

### ISSUE THREAD

**Issue by jeremoquai** [BroHui/python-yeast#1]
hello

sorry for the newbie question

>>> import yeast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jeremie\Dropbox\perso\projects\python\winamax\yeast.py", line 47
    print yeast()
          ^
SyntaxError: invalid syntax

what is going wrong ?

thanks !

**Comment by BroHui** [comment]
The tools was writen by Python2.7, and it seems you're running it by Python3.

**Comment by jeremoquai** [comment]
thanks @BroHui 

not very familiar with Python versions : hard to re-write it for Python 3 ?

**Comment by BroHui** [comment]
You can git pull the lastest file, I've upgrade the main file to Python3.

**Comment by jeremoquai** [comment]
thanks lot !
